Update the repo (#5)
* Update pre-commit hook

* Ensure that the lint-go script can run and give directions if it can't

* Use /usr/bin/env bash for everything

* Add tools target and some help text

* Separate the dod-iac imports from everything else

* Update terraform docs version

* Update golang binary

* Fix imports

* Add an editorconfig for formatting between editors.

diff --git a/scripts/lint-go b/scripts/lint-go
--- a/scripts/lint-go
+++ b/scripts/lint-go
@@ -1,4 +1,4 @@
-#!/bin/bash
+#! /usr/bin/env bash
 
 # =================================================================
 #
@@ -11,16 +11,31 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 set -eu
 
 # move up a directory
-cd $DIR/..
+cd "${DIR}"/..
 
 pkgs=$(go list ./... | grep -v /vendor/ | tr "\n" " ")
+
+check_command () {
+  cmd=$1
+
+  if ! command -v "bin/${cmd}" > /dev/null; then
+    echo "Missing ${cmd}, please install into bin/ directory with 'make bin/${cmd}'"
+    exit 1
+  fi
+}
+
+# Validate that the commands exist
+check_command errcheck
+check_command ineffassign
+check_command shadow
+check_command staticcheck
 
 echo "******************"
 echo "Running go vet"
 go vet $pkgs
 echo "******************"
 echo "Running go vet with shadow"
-go vet -vettool="bin/shadow" $pkgs
+go vet -vettool="${DIR}/../bin/shadow" $pkgs
 echo "******************"
 echo "Running errcheck"
 bin/errcheck ${pkgs}
